name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install Dependencies
      run: npm install
      
    - name: tests
      run:  npm run test

  integration-test-ng10:
    name: integration-test-ng10
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install Dependencies
      run: npm install

    - name: create package
      run:  npm run remove-all-tgz && npm run pack-tgz

    - name: copy package to integration directory
      run:  npm run integration-tests:copy-to-tests   
         
    - name: install package to angular and list installed packages
      run:  npm run integration-tests:install:ng10 && npm run integration-tests:list-installs:ng10

    - name: print angular version
      run:  npm run integration-tests:version:ng10

    - name: angular build
      run:  npm run integration-tests:build:ng10

    - name: run angular integration test
      run:  npm run integration-tests:test-ci:ng10

    # - name: Create package to ./dist
    #   run:  npm run pack-to-dist-directory

    # - name: Create artifact from ./dist
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: angular-typesafe-reactive-forms-helper
    #     path: ./dist
